### ISSUE TITLE
Either StripeProvider or InjectStripe is stripping child component props

### ISSUE THREAD

**Issue by fholgado** [stripe/react-stripe-elements#352]
### Summary

Hi folks! I am attempting to pass props to a child node of `<StripeProvider />`. It seems like as part of transforming the child object, props are not being re-applied to the child as it's rendered. I am following the structure shown in the readme. Example:

In parent component:
```
        <StripeProvider apiKey="pk_123">
            <CheckoutForm foo="baz"/>
        </StripeProvider>
```

In `<CheckoutForm />`, I'm exporting the component using `injectStripe`.
```
export default injectStripe(CheckoutForm);

```
Inside `CheckoutForm`, `this.props.foo` is always undefined, and the only prop that ever makes it is `this.props.stripe`. What am I missing? I 

Thanks in advance!

**Comment by asolove-stripe** [comment]
@fholgado Yikes, that's no good. I have a failing test for this and it's definitely `injectStripe` that is stripping the props. I'll work on a fix and hope to have it released before too long. 

In the interim, I hope you found a solution by juggling the way props get passed down in your application.

**Comment by fholgado** [comment]
Thanks so much! I have a workaround I can use in the meantime, but it involves saving state to the ‘window’ object, so it’s not great 😂

––
Fed

**Comment by asolove-stripe** [comment]
Hey @fholgado could you share some of the code or a minimal reproduction? (Privately by email is fine if it's sensitive.) My supposed reproduction was actually just a poorly-written test. It appears that this currently works fine:

```js
const Child = (props) => <div>{props.text}</div>;
const InjectedChild = injectStripe(Child);
const Parent = () => <InjectedChild text="Hello, world!"/>
```

The `text` props gets passed down and render by the `Child`. I'm curious if you're doing something different from this or what specifically you are seeing.

**Comment by fholgado** [comment]
Ok. Let's see:

I've got an `App/index.jsx` file that contains my router and app wrapper. One of the routes to my checkout form looks like this:

```
    CheckoutFormRoute = ({match}) => {
        return (
            <StripeProvider apiKey="blah">
                <CheckoutForm checkoutState={this.state.checkoutState} />
            </StripeProvider>
        );
    }

The `CheckoutForm` component is nothing special, and uses the `InjectStripe` HOC to wrap the return:

```
export default injectStripe(CheckoutForm);
```

I wonder if that combination of `StripeProvider` and `InjectStripe` is what's causing the issue?

**Comment by asolove-stripe** [comment]
Ah, interesting! I had tried testing a provider with a child with a prop, and another parent passing a prop to the injected child. But this bug appears to happen only when it is exactly this setup: the provider with the injected component as its immediate child. I've now got a failing test and will look into a fix.

**Comment by asolove-stripe** [comment]
@fholgado When you try to run your code in the current state, do you see an error in the console that says something like: 

```inject.js:46 Uncaught Error: It looks like you are trying to inject Stripe context outside of an Elements context.
Please be sure the component that calls createSource or createToken is within an <Elements> component.```

I think you'll want the overall hierarchy to be StripeProvider -> Elements -> injectStripe(CheckoutForm). Injecting the stripe object without being inside an `Elements` component is going to produce some unexpected behavior.

Now, we definitely have some more work to do to make this clearer in the docs. And if your app isn't getting that console warning, then we should fix that too.

**Comment by fholgado** [comment]
Hey Adam. You were totally right. I missed the `<Element>` HOC when following the getting started guide. I didn't notice anything too weird in that scenario other than the `props` missing, and there was nothing in the console that was throwing a warning. Thanks so much for your help, and sorry for it being a dumb mistake on my part.

**Comment by D19cannon** [comment]
Heey @asolove-stripe , I am still having this issue. I followed the comments and the solution that has been mentioned with zero success...

Long story short I tried the way @fholgado mentioned
```
 <StripeProvider apiKey='....'>
   <Elements>
      <StripePayment />
   </Elements>
</StripeProvider>
```

I checked of there were any props in the <StripePayment />, but the prop object is empty. Thus, the strip() etc. are not working.

Also, I was wondering how  I am suppose to send the api request on submission? I've been going through the documents quite a few times for a couple of days now. But there is no example how to make my own custom submission. 

I did like to have an alternative option in case I want something a more customised, since I am using WP, WP-Woocommerce, Gatsby, Apollo. And for that reason I don't want my products to be stored in stripe with the products unique sku from stripe (seems a bit odd to have my products duplicated at two services), but only have the payment confirmation that response a success/fail.
